config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/index', to: 'welcome#index'
	
  resources :users, only: [:new, :create]
  get '/registrate', to: 'users#new'
  get '/ranking', to: 'users#show'

  resources :guides
  get '/guides', to: 'guides#index'
  #post '/users/:id/guides/new', to: 'guides#new'

  resources :profiles

  resource :session, only: [:new, :create, :destroy]
  get 'login' => "sessions#new", as: "login"
  get 'logout' => "sessions#destroy", as: "logout"
  #resources :profiles do
  #  member do
  #    get :edit
  #  end
  #end
end

app/models/profile.rb
class Profile < ApplicationRecord
  mount_uploader :photo, ImageUploader
  belongs_to :user, optional: true 
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

	def create
	@user = User.find(params[:user_id])
	@profile = @user.profile.create(profile_params)
    #redirect_to({action: :profile}, notice: 'art no encontrado') unless @profile
	redirect_to profile_path(@profile)
  end
	def new 
	end 

	def show 
	@profile = Profile.find(params[:user_id])
	end 

    private 
    def profile_params
      params.require(:profile).permit(:points, :bio, :categorie)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = Profile.new
  end

  def show
    @user = User.find_by_id(params[:id])
    @profile = @user.profile
  end

  def edit
   @profile = Profile.find_by_id(params[:id])
   redirect_to root_path, alert: "Operación no permitida." unless @profile
  end
 
  def update
    @profile = Profile.find_by_id(params[:id])
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Perfil actualizado.' }
      else
        format.html { render :edit }
      end
    end
  end 

  def profile_params
      params.require(:profile).permit(:points, :bio, :categorie, :photo, :user_id)
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true, html: {multipart: true}) do |form| %>
  
  <div class="field">
    <%= form.label :"Foto Principal" %>
    <%= form.file_field :photo, id: :profile_photo %>
  </div><br>

  <div class="field">
    <%= form.label :Biografía %>
    <%= form.text_area :bio, id: :profile_bio %>
  </div>

  <div class="actions">
    <%= form.submit :"Guardar Cambios" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<% if @profile.id == current_user.id %>
  <h3>Editar Perfil</h3>

  <%= render 'form', profile: @profile %>

<% else %>
  <%= controller.redirect_to root_path %>
<% end %>

app/views/profiles/form.html.erb
<h3> Editar Perfil <h3>		
<%= form_with(model: @profile, local: true, html: {multipart: true}) do |form| %>

  <div class="field">
    <%= form.label :bio %>
   <%= form.text_area :bio, id: :profile_bio %>
   
  </div>
  

  <div class="actions">
    <%= form.submit :"Guardar Cambios" %>
  </div>
<% end %>

app/views/profiles/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Perfil de Usuario</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="profileNavbar.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="logoStyle.css">
    <link rel="stylesheet" href="style.css">
</head>
<body>
<body>
<div id="guiajuegos" class="icon">
    <div class="fbox">
        <div class="guia"><a href="index.html">Guia</a></div>
        <div class="juegos"><a href="index.html">Juegos</a></div>
    </div>
</div>

<div class="menu">
    <ul class="nav">
        <li><a href="">PS4</a></li>
        <li><a href="">XBOX</a></li>
        <li><a href="">PC</a></li>
        <li><a href="">FORO</a></li>
    </ul>

    <ul class="nav">
        <li><a href="">Noticias</a></li>
        <li><a href="">Analisis</a></li>
        <li><a href="ranking.html">Ranking</a></li>
        <li><a href="guides.html">Guias</a></li>
        <li><a href="">Eventos</a></li>
        <li><a href="">Logros</a></li>
        <li><a href="">Trucos</a></li>
        <li><a href="formulario.html">¡Regístrate!</a><li>
    </ul>
</div>

<div id="fondoPerfil">
    <div id="imagenUsuario">
        <img src="image/usuario.jpg">
    </div>
</div>



<div id="contenido">
    <div id="principal">
        <div class="menu menuAportes">
            <ul>
                <li><a class="noReload" href="myPosts.html">Mis Aportes</a></li>
                <li><a class="noReload" href="myValuations.html">Mis Valoraciones</a></li>
                <li><a class="noReload" href="trending.html">Trending</a></li>
            </ul>
        </div>
        <div id="page" class="fondoTablon"></div>
    </div>

    <div id="lateral">
        <div id="rolUsuario">
            <div class="inline">
		<% user = User.last%>
		<% profile = Profile.last%>
               
            </div>
            <div class="inline">
               <h6><%= profile.categorie %></h6>
            </div>
            <div class="inline">
		
                <h6><%= user.name %></h6> 
            </div>
            <div class="inline">
                <h6><%= profile.points %> Puntos </h6>
            </div>
        </div>
	<div >
		<p> Biografia: <%= profile.bio %></p>
 
      <span class="actions">

       <h5><%= link_to "editar", form_profile_path(user) %></h5>
      </span>

	</div>
        

        <div class="fondoLateral">
            <h6 class="tituloTablon">Stats</h6>
            <div class="inline">
                <ul class="nostyle">
                    <li><strong>Colaboraciones:</strong> X</li>
                    <li><strong>Comentarios:</strong> X</li>
                    <li><strong>Valoraciones:</strong> X</li>
                </ul>
                <ul class="nostyle">
                    <li><strong>Valoraciones recibidas:</strong> X</li>
                    <li><strong>Hilos creados:</strong> X</li>
                </ul>
            </div>
        </div>
        <div class="fondoLateral">
            <h6 class="tituloTablon">Mis Estadísticas</h6>
            <ul class="nostyle">
                <li><strong>01/12/2017</strong> +X Puntos</li>
                <li><strong>13/11/2017</strong> +X Puntos</li>
                <li><strong>30/10/2017</strong> -X Puntos</li>
                <li><strong>19/10/2017</strong> +X Puntos</li>
                <li><strong>21/09/2017</strong> -X Puntos</li>
            </ul>
        </div>
    </div>
</div>

app/views/profiles/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Perfil de Usuario</title>
</head>
<body>
<body>
<div id="fondoPerfil">
    <div id="imagenUsuario">
        <% if @profile.photo.blank? %>
          <%= image_tag('usuario.jpg', alt: "Foto de Perfil1") %>
        <% else %>
          <%= image_tag(@profile.photo, alt: "Foto de Perfil") %>
        <% end %>
    </div>
</div>

<div id="contenido">
    <div id="principal">
        <div class="menu menuAportes">
            <ul>
                <li><a class="noReload" href="myPosts.html">Mis Aportes</a></li>
                <li><a class="noReload" href="myValuations.html">Mis Valoraciones</a></li>
                <li><a class="noReload" href="trending.html">Trending</a></li>
            </ul>
        </div>
        <div id="page" class="fondoTablon"></div>
    </div>

    <div id="lateral">
        <div id="rolUsuario">
            <div class="inline">
               <h6><%= @profile.categorie %></h6>
            </div>
            <div class="inline">
                <h6><%= @user.name %></h6> 
            </div>
            <div class="inline">
                <h6><%= @profile.points %> Puntos </h6>
            </div>
        </div>
	<div >
	  <p> Biografia: <%= @profile.bio %></p>
	  <% if logged_in? %>
            <% if @user.id == current_user.id %>
              <span class="actions">
                <h5><%= link_to "editar", edit_profile_path(current_user) %></h5>
              </span>
            <% end %>
	  <% end %>
	</div>
        <div class="fondoLateral">
            <h6 class="tituloTablon">Stats</h6>
            <div class="inline">
                <ul class="nostyle">
                    <li><strong>Colaboraciones:</strong> X</li>
                    <li><strong>Comentarios:</strong> X</li>
                    <li><strong>Valoraciones:</strong> X</li>
                </ul>
                <ul class="nostyle">
                    <li><strong>Valoraciones recibidas:</strong> X</li>
                    <li><strong>Hilos creados:</strong> X</li>
                </ul>
            </div>
        </div>
        <div class="fondoLateral">
            <h6 class="tituloTablon">Mis Estadísticas</h6>
            <ul class="nostyle">
                <li><strong>01/12/2017</strong> +X Puntos</li>
                <li><strong>13/11/2017</strong> +X Puntos</li>
                <li><strong>30/10/2017</strong> -X Puntos</li>
                <li><strong>19/10/2017</strong> +X Puntos</li>
                <li><strong>21/09/2017</strong> -X Puntos</li>
            </ul>
        </div>
    </div>
</div>