config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/index', to: 'welcome#index'
	
  resources :users, only: [:new, :create]
  get '/registrate', to: 'users#new'
  get '/ranking', to: 'users#show'

  resources :guides
  get '/guides', to: 'guides#index'
  #post '/users/:id/guides/new', to: 'guides#new'

  resources :profiles

  resource :session, only: [:new, :create, :destroy]
  get 'login' => "sessions#new", as: "login"
  get 'logout' => "sessions#destroy", as: "logout"
  #resources :profiles do
  #  member do
  #    get :edit
  #  end
  #end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :guide
 
	scope :published, ->{where("comments.published_at IS NOT NULL")}

	validates :published_at, presence: true
end

app/models/guide.rb
class Guide < ApplicationRecord
  mount_uploader :photo, ImageUploader

  belongs_to :user, optional: true
  has_many :comments

  scope :guide, -> {select('guides.id, guides.user_id, guides.photo, guides.title, guides.body, guides.updated_at, users.name').joins(:user)}
  scope :guide_list, -> {select('guides.id, guides.user_id, guides.photo, guides.title, guides.updated_at, guides.trophies, guides.category, users.name').joins(:user).limit(10)}
  validates :body, :title, :trophies, :category, presence: {message: "el campo no puede quedar vacío"}
  validates :photo, presence: {message: "Debe añadir una foto"}
 
end

app/models/profile.rb
class Profile < ApplicationRecord
  mount_uploader :photo, ImageUploader
  belongs_to :user, optional: true 
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_new_password
  after_create :build_profile

  has_one :profile
  has_many :guides, ->{order('updated_at DESC')}, dependent: :nullify
  has_many :replies, through: :guides, source: :comments

  scope :rank, -> {select('users.id, users.name, profiles.points').joins(:profile).order('points DESC').limit(10)}

  def build_profile
    Profile.create(user: self, points: 0, bio: "Hey im here using guiajuegos", categorie:"Novato", photo: '/assets/images/usuario.jpg')
  end
	
  validates :email, uniqueness: {case_sensitive: false, message: 'El correo introducido no es único'}, length: {in: 12..20, too_short: "debe tener al menos 12 caracteres"}, format: {multiline: true,with: /^.+@.+$/, message: "formato de correo no valido"}
  validates :name, uniqueness: {case_sensitive: true, message:'Este nombre ya esta siendo usado'}, length: {in: 4..10, too_short: "El nombre debe tener al menos 4 caracteres"}
  validates :password, confirmation: true, length: {within: 6..20}, presence: true
  validates :password_confirmation, presence: true

  def self.authenticate(name,password)
    user = find_by_name(name)
    return user if user && user.authenticated?(password)
  end
  
  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end
  
  protected
  def encrypt_new_password
    return if password.blank?
    self.hashed_password = encrypt(password)
  end
  def password_required?
    hashed_password.blank? || password.present?
  end
  def encrypt(string)
    Digest::SHA1.hexdigest(string) 
  end

end

app/models/welcome.rb
class Welcome < ApplicationRecord
has_many :users
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :load_guide, except: :destroy
  before_action :authenticate, only: :destroy
  
  def create
    @comment = @guide.comments.new(comment_params)
    if @comment.save
      redirect_to @guide, notice: 'gracias por su comentario'
    else
      redirect_to @guide, alert: 'no ha sido posible añadir el comentario'
    end
  end
  
  def destroy
    @guide = current_user.guides.find_by_id(params[:guide_id])
    if @guide.nil?
       redirect_to :index, notice: "operación no permitida"
     end
    @comment = @guide.comments.find_by_id(params[:id])
    @comment.destroy
    redirect_to @guide, notice: "comentario eliminado"
  end
  
  private
    def load_guide
      @guide = Guide.find_by_id(params[:guide_id])
    end
    
    def comment_params
      params.require(:comment).permit(:name, :email, :body)
    end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  before_action :set_guide, only: [:show]

  def new 
    @guide = Guide.new
  end

  def create
    @guide = current_user.guides.new(guide_params)

    respond_to do |format|
      if @guide.save
        format.html { redirect_to @guide, notice: 'Guía creada correctamente.' }
      else
        format.html { render :new }
      end
    end
  end
  

  def edit
   @guide = Guide.find_by_id(params[:id])
   redirect_to root_path, alert: "Operación no permitida." unless @guide
  end

  def update
    @guide = Guide.find_by_id(params[:id])
    respond_to do |format|
      if @guide.update(guide_params)
        format.html { redirect_to @guide, notice: 'Guía Actualizada.' }
      else
        format.html { render :edit }
      end
    end
  end 

 def destroy
    @guide = current_user.guides.find(params[:id])
    @guide.destroy
    respond_to do |format|
      format.html { redirect_to guides_url, notice: 'La guía fue eliminada.' }
    end
  end
  
  def index
   @guides = Guide
		.guide_list	

  end 

  def show
    redirect_to({action: :index}, notice: 'Guía no encontrada.') unless @guide
  end

  private
  def set_guide
      @join = Guide
		  .guide
      @guide = @join.find_by_id(params[:id])
  end

  def guide_params
      params.require(:guide).permit(:title, :body, :photo, :category,:trophies,:user_id)
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

<div class="menu">
    <ul>
        <li><a href="">PS4</a></li>
        <li><a href="">XBOX</a></li>
        <li><a href="">PC</a></li>
        <li><a href="">FORO</a></li>

    </ul>

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

	def create
	@user = User.find(params[:user_id])
	@profile = @user.profile.create(profile_params)
    #redirect_to({action: :profile}, notice: 'art no encontrado') unless @profile
	redirect_to profile_path(@profile)
  end
	def new 
	end 

	def show 
	@profile = Profile.find(params[:user_id])
	end 

    private 
    def profile_params
      params.require(:profile).permit(:points, :bio, :categorie)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = Profile.new
  end

  def show
    @user = User.find_by_id(params[:id])
    @profile = @user.profile
  end

  def edit
   @profile = Profile.find_by_id(params[:id])
   redirect_to root_path, alert: "Operación no permitida." unless @profile
  end
 
  def update
    @profile = Profile.find_by_id(params[:id])
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Perfil actualizado.' }
      else
        format.html { render :edit }
      end
    end
  end 

  def profile_params
      params.require(:profile).permit(:points, :bio, :categorie, :photo, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: "Registro completado con éxito. Verifique su correo para iniciar sesión."
    else
      render action: :new
    end
  end

  def show
    @users = User
		.rank
  end

 private
   def set_user
     @user = current_user
   end

  def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
 

def index
 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %> 
  <h3>
    <%= comment.guide_id %> &lt; said:
    <% if @guide.owned_by? current_user %> 
      <span class="actions">
         <%= link_to "delete",guide_comment_path(guide_id: @guide, id: comment), method: :delete, data: {confirm: "seguro?"} %> 
      </span>
     <% end %> 
  </h3>
   <%= comment.body %> 
<% end %> 

app/views/guides/_form.html.erb
<%= form_with(model: guide, local: true, html: {multipart: true}) do |form| %>
  <div class="field">
    <%= form.label :Título %><br>
    <%= form.text_field :title, id: :guide_title %>
  </div><br>

  <div class="field">
    <%= form.label :Contenido %><br>
    <%= form.text_area :body, id: :guide_body %>
  </div><br>

  <div class="field">
    <%= form.label :Trofeos %><br>
    <%= form.number_field :trophies, id: :guide_trophies %>
  </div><br>

  <div class="field">
    <%= form.label :Categoría %><br>
    <%= form.text_field :category, id: :guide_category %>
  </div><br>
  
  <div class="field">
    <%= form.label :"Foto Principal" %>
    <%= form.file_field :photo, id: :guide_photo %>
  </div><br>

  <div class="field">
    <%= form.hidden_field :user_id, id: :guide_author_id %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar"%>
  </div>
<% end %>

app/views/guides/edit.html.erb
<% if @guide.user_id == current_user.id %>
  <h3>Editar Guía</h3>

  <%= render 'form', guide: @guide %>

<% else %>
  <%= controller.redirect_to root_path %>
<% end %>

app/views/guides/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Guias</title>

</head>
<body>


<div>

    <div id="contenido" class="container">

        <div id="principal">
            <h2 style="margin-left: 30%" class="ranking">Guías</h2>

            <form id="Genero" action="">

                <select name="Genero">
                    <option value="Accion">Accion</option>
                    <option value="Ciencia Ficcion">Ciencia Ficcion</option>
                    <option value="Misterio">Misterio</option>
                    <option value="Deportes">Deportes</option>
                </select>
                <br><br>
            </form>
           <% if logged_in? %>
           <div class="guia"><%= link_to " + Crear guia", new_guide_path %></div>
            <% end %>

            <div class="menuGuias">
                <ul>
                    <li class="enlaces"><a href="">A</a></li>
                    <li class="enlaces"><a href="">B</a></li>
                    <li class="enlaces"><a href="">C</a></li>
                    <li class="enlaces"><a href="">D</a></li>
                    <li class="enlaces"><a href="">E</a></li>
                    <li class="enlaces"><a href="">F</a></li>
                    <li class="enlaces"><a href="">G</a></li>
                    <li class="enlaces"><a href="">H</a></li>
                    <li class="enlaces"><a href="">I</a></li>
                    <li class="enlaces"><a href="">J</a></li>
                    <li class="enlaces"><a href="">K</a></li>
                    <li class="enlaces"><a href="">L</a></li>
                    <li class="enlaces"><a href="">M</a></li>
                    <li class="enlaces"><a href="">N</a></li>
                    <li class="enlaces"><a href="">O</a></li>
                    <li class="enlaces"><a href="">P</a></li>
                    <li class="enlaces"><a href="">Q</a></li>
                    <li class="enlaces"><a href="">R</a></li>
                    <li class="enlaces"><a href="">S</a></li>
                    <li class="enlaces"><a href="">T</a></li>
                    <li class="enlaces"><a href="">U</a></li>
                    <li class="enlaces"><a href="">V</a></li>
                    <li class="enlaces"><a href="">W</a></li>
                    <li class="enlaces"><a href="">X</a></li>
                    <li class="enlaces"><a href="">Y</a></li>
                    <li class="enlaces"><a href="">Z</a></li>
                </ul>
            </div>

           <table id="espaciado" class="table table-striped">
            <tbody>
	    <% @guides.each do |guide| %>
                <tr>
                    <td><%= link_to image_tag(guide.photo), guide_path(guide.id) %></td>
                    <td><%= link_to guide.title, guide_path(guide.id) %></td>
           	    <td><%= guide.category %></td>
		    <td><%= guide.trophies %> trofeos</td>
                    <td>Autor:<%= guide.name %></td>
                    <td>
                        <% if logged_in? %>
                          <% if guide.user_id == current_user.id %>
                             <span class="actions">
                             <h5><%= link_to "Editar", edit_guide_path(guide.id) %></h5>
                             <h5><%= link_to "Eliminar", guide, method: :delete, data: {confirm: "seguro??"} %></h5>
                            </span>
                          <% end %>
	                <% end %>
                    </td>
                </tr>
	    <% end %>
            </tbody>
        </table>
                    

        <div>
            <div id="lateralGuias" class="lateralBorder">

                <h5 class="titulillo"> Mas Recientes</h5>
                <img src="image/bloodborne.jpg" alt="Blood Borne">
                <a class="auto1" href=""> Nuevo jefe para BloodBorne </a>

                <img src="image/bluedragon.jpg" alt="blue dragon">
                <a class="auto1" href=""> Blue dragon el poder del fuego.</a>

                <img src="image/starwars.jpg" alt="foto de consola">
                <a class="auto1" href="">Los secretos tras Star Wars</a>

                <img class="tamg" src="image/sega.jpg" alt="Sega">
                <a class="auto1" href="">Posible nuevo juego para Sega</a>
            </div>
        </div>
    </div>
</div>
</body>
</html>

app/views/guides/new.html.erb
<h1>Nueva Guía</h1>

<%= render 'form', guide: @guide %>

app/views/guides/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>show of guides</title>
</head>
<body>
<div>
    <div id="contenido" class="container">
        <div id="principal">

            <h2 style="margin-left: 30%" class="ranking"><%= @guide.title %></h2>

            <p><%= @guide.name %> | <%= @guide.updated_at %></p>

            <div style="padding: 2% 3% 2% 0"><%= image_tag(@guide.photo) %></div>
            <p><%= @guide.body %></p>

            <h7>¡Déjanos tu comentario! (@guide.comments.count)</h7>
	    <%= render file:'comments/new' %> 
        </div>

        <div>
            <div id="lateralGuias" class="lateralBorder">
                <h5 class="titulillo"> Mas Recientes</h5>
                <img src="image/bloodborne.jpg" alt="Blood Borne">
                <a class="auto1" href=""> Nuevo jefe para BloodBorne </a>

                <img src="image/bluedragon.jpg" alt="blue dragon">
                <a class="auto1" href=""> Blue dragon el poder del fuego.</a>

                <img src="image/starwars.jpg" alt="foto de consola">
                <a class="auto1" href="">Los secretos tras Star Wars</a>

                <img class="tamg" src="image/sega.jpg" alt="Sega">
                <a class="auto1" href="">Posible nuevo juego para Sega</a>
            </div>
        </div>
    </div>
</div>
</body>
</html>

app/views/users/form.html.erb
<h3> Editar Perfil <h3>		
<%= form_with(model: @user, local: true, html: {multipart: true}) do |form| %>

  <div class="field">
    <%= form.label :biografia %>
   <%= form.text_area :Biografia, id: :user_biografia %>
   
  </div>
  

  <div class="actions">
    <%= form.submit :"Actualizar" %>
  </div>
<% end %>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Formularios</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="logoStyle.css">
    <link rel="stylesheet" href="style.css">
    <script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.12.3/jquery.min.js\"></script>
</head>

<body>


<div id="contenido">
    <div id="wrapper">
        <h2>¡Regístrate YA!</h2>

<%= form_with(model: @user, local: true) do |form| %>

   <div class="field">
    <%= form.label :"Nombre: " %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :"Email: " %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :"Contraseña: " %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :"Repetir contraseña: " %>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation %>
  </div>
  

  <div class="actions">
    <%= form.submit :"Registrarte" %>
  </div>
<% end %>

</div>
</div>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ranking de usuarios</title>
</head>

<div id="contenido">

    <div class="container">
        <h2 class="ranking">Ranking de Usuarios</h2>

        <div class="menu rankingMenu">
            <ul id="ranking">
                <li><a href="">Diario</a></li>
                <li><a href="">Mensual</a></li>
                <li><a href="">Anual</a></li>
            </ul>
        </div>

        <table id="espaciado" class="table table-striped">
            <thead>
            <tr style="background-color: cornflowerblue">
                <th>#</th>
                <th>Nick</th>
                <th>Puntos</th>
            </tr>
            </thead>
            <tbody>
	    <% @users.each_with_index do |user, index| %>
                <tr>
                    <td><%= index+1 %></td>
           	    <td><%= user.name %></td>
		    <td><%= user.points %></td>
                </tr>
	    <% end %>
            </tbody>
        </table>
    </div>
</div>
</body>
</html>

app/views/welcome/index.html.erb
<head>
  <%= javascript_include_tag "https://code.jquery.com/jquery-3.2.1.slim.min.js" %>
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" %>
</head>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="margin-top: 0%">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <%= image_tag "nintendo.jpg", size:"1000x430" %> 
            <div class="carousel-caption d-none d-md-block"></div>
        </div>

        <div class="carousel-item">
            <%= image_tag "overwatch-ed.jpg", size:"1000x430" %>
            <div class="carousel-caption d-none d-md-block"></div>
        </div>

        <div class="carousel-item">
            <%= image_tag "callof.jpg", size:"1000x430" %>
            <div class="carousel-caption d-none d-md-block">
                <h3>Call Of Duty : Por fin ha vuelto</h3>
            </div>
        </div>
    </div>

    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>

    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<!-- div para seccion de noticias -->
<div id="contenido" class="center">
    <div id="principal">
        <h2 class="titulo">Últimas Noticias</h2>

        <div class="inline">
            <div class="auto"> <!-- div de primera noticia-->
                <h3><a href="">Disney compra 21 fox</a></h3>
                <div><%= image_tag "disney.jpg", class: "tamg" %></div>
                <p>El juego en el que todos piensan </p>
            </div>

            <div>
                <h3><a href="">Battlefield</a></h3>
                <div><%= image_tag "call.jpg", class: "tamg" %></div>
                <p>El juego en el que todos piensan </p>
            </div>
        </div>

        <div class="inline">
            <div class="auto1"> <!-- div de primera noticia-->
                <h3><a class="tam" href="">Civil Aviones</a></h3>
                <div><%= image_tag "avion.jpg", class: "tam" %></div><!--div para  imagen -->
                <p>El juego en el que todos piensan </p><!--cambios-->
            </div>

            <div class="auto1"> <!-- div de primera noticia-->
                <h3><a class="tam" href="">Pokemon Cristal</a></h3>
                <div><%= image_tag "pokemon.jpg", class: "tam" %></div>  <!--div para  imagen -->
                <p>El juego en el que todos piensan </p><!--cambios-->
            </div>

            <div class="auto1"> <!-- div de primera noticia-->
                <h3><a class="tam" href="">Final Fantasy</a></h3>
                <div><%= image_tag "muneco.jpg", class: "tam" %><!--div para  imagen -->
                <p>El juego en el que todos piensan </p><!--cambios-->
            </div>
        </div>

        <!-- div para seccion de noticias -->
        <div style="padding-top: 5%">
            <h2 class="titulo">Análisis Destacados</h2>

            <div class="inline">
                <div class="auto"> <!-- div de primera noticia-->
                    <h3><a href="">Animal Crossing</a></h3>
                    <div><%= image_tag "animal.jpg", class: "tamg" %></div>
                    <!--div para  imagen -->
                    <p>El juego en el que todos piensan </p>
                </div>

                <div>
                    <h3><a href="">Tekken</a></h3>
                    <%= image_tag "teken.jpg", class: "tamg" %><!--div para  imagen -->
                    <p>El juego en el que todos piensan </p>
                </div>
            </div>

            <div class="inline">
                <div class="auto1"> <!-- div de primera noticia-->
                    <h3><a class="tam" href="">The Hunter</a></h3>
                    <div><%= image_tag "hunter.jpg", class: "tam" %></div>
                    <!--div para  imagen -->
                    <p>El juego en el que todos piensan </p><!--cambios-->
                </div>

                <div class="auto1"> <!-- div de primera noticia-->
                    <h3><a class="tam" href="">Player underground</a></h3>
                    <div><%= image_tag "pubg.jpg", class: "tam" %></div>
                    <!--div para  imagen -->
                    <p>El juego en el que todos piensan </p><!--cambios-->
                </div>

                <div class="auto1"> <!-- div de primera noticia-->
                    <h3><a class="tam" href="">Metroid</a></h3>
                    <div><%= image_tag "futurista.jpg", class: "tam" %></div>
                    <p>El juego en el que todos piensan </p>
                </div>
            </div>
        </div>
    </div>

    <div id="lateral" class="lateralBorder">
        <h5 class="titulillo"> Últimos Trucos</h5>
        <%= image_tag "pubg.jpg" %>
        <p>Desbloquear rifle </p>

        <%= image_tag "bluedragon.jpg" %>
        <p>Como desbloquear el pico de oro</p>

        <h5 class="titulillo">Últimos Logros</h5>
        <%= image_tag "psp.jpg" %>
        <p>Logro: Viejo pero sabio</p>

        <%= image_tag "coche.jpg", class: "tamg" %>
        <p>Logro: Fast and Furious</p>

        <h5 class="titulillo"> Ranking de Usuarios</h5>
        <div class="menu">
            <ul id="ranking">
                <li class="ranking"><a href="">Diario</a></li>
                <li class="ranking"><a href="">Mensual</a></li>
                <li class="ranking"><a href="">Anual</a></li>
            </ul>
        </div>

        <table id="espaciado" class="table table-striped">
            <thead>
            <tr style="background-color: cornflowerblue">
                <th>#</th>
                <th>Nick</th>
                <th>Puntos</th>
            </tr>
            </thead>

            <tbody>
            <div>
                <tr>
                    <td>1</td>
                    <td>
                        <div class="dropdown">
                            <img class="ranking" src="image/usuario.jpg">Nicky
                            <div class="dropdown-content">
                                <%= image_tag "usuario.jpg", size: "100x100" %>
                                <div class="desc"><h6>Nicky</h6>
                                    <h6> Bio: le gusta jugar al tennis</h6>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td>3000</td>
                </tr>

                <tr>
                    <td>2</td>
                    <td>
                        <div class="dropdown">
                            <img class="ranking" src="image/usuario.jpg">Mickey
                            <div class="dropdown-content">
                                <%= image_tag "usuario.jpg", size: "100x100" %>
                                <div class="desc"><h6>Mickey</h6>
                                    <h6> Bio: le gusta jugar al tennis</h6>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td>2000</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td><img class="ranking" src="image/usuario.jpg">Laura</td>
                    <td>1000</td>
                </tr>
            </div>
            </tbody>
        </table>
    </div>
</div>